<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 5.0.1 (Python 3.10.5 on win32)" generated="20220714 14:17:53.277" rpa="false" schemaversion="3">
<suite id="s1" name="SignUp Form" source="C:\Users\chnga\PycharmProjects\AluTest\Testcases\Signup_Form\SignUp_Form.robot">
<kw name="Open Sign_Up Page" type="SETUP">
<msg timestamp="20220714 14:17:53.435" level="FAIL">No keyword with name 'Open Sign_Up Page' found.</msg>
<status status="FAIL" starttime="20220714 14:17:53.435" endtime="20220714 14:17:53.435"/>
</kw>
<test id="s1-t1" name="Invalid_testcase" line="19">
<status status="FAIL" starttime="20220714 14:17:53.435" endtime="20220714 14:17:53.435">Parent suite setup failed:
No keyword with name 'Open Sign_Up Page' found.</status>
</test>
<kw name="Close All Browsers" library="SeleniumLibrary" type="TEARDOWN">
<doc>Closes all open browsers and resets the browser cache.</doc>
<status status="PASS" starttime="20220714 14:17:53.450" endtime="20220714 14:17:53.450"/>
</kw>
<status status="FAIL" starttime="20220714 14:17:53.293" endtime="20220714 14:17:53.450">Suite setup failed:
No keyword with name 'Open Sign_Up Page' found.</status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="SignUp Form">SignUp Form</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20220714 14:17:53.419" level="ERROR">Error in file 'C:\Users\chnga\PycharmProjects\AluTest\Testcases\Signup_Form\SignUp_Form.robot' on line 4: Variable file '..\PageObjects\Signup_form.py' does not exist.</msg>
<msg timestamp="20220714 14:17:53.419" level="ERROR">Error in file 'C:\Users\chnga\PycharmProjects\AluTest\Testcases\Signup_Form\SignUp_Form.robot' on line 5: Variable file '..\TestData\Testdata.py' does not exist.</msg>
<msg timestamp="20220714 14:17:53.419" level="ERROR">Error in file 'C:\Users\chnga\PycharmProjects\AluTest\Testcases\Signup_Form\SignUp_Form.robot' on line 6: Resource file '..\Resources\PLP_Keywords.robot' does not exist.</msg>
<msg timestamp="20220714 14:17:53.435" level="ERROR">Error in file 'C:\Users\chnga\PycharmProjects\AluTest\Testcases\Signup_Form\SignUp_Form.robot' on line 8: Resource file '..\Resources\SignUP_Form_Keywords.robot' does not exist.</msg>
<msg timestamp="20220714 14:17:53.435" level="ERROR">[ DataDriver ] Error in robot file:
  File "C:\Users\chnga\PycharmProjects\AluTest\Testcases\Signup_Form\SignUp_Form.robot", line 0</msg>
<msg timestamp="20220714 14:17:53.435" level="ERROR">In source file:
  File "../TestData/Testdata_Signup.xlsx", line 0</msg>
<msg timestamp="20220714 14:17:53.435" level="ERROR">Calling method '_start_suite' of listener 'DataDriver' failed: FileNotFoundError: File attribute was not a full path. Tried to find C:\Users\chnga\PycharmProjects\AluTest\Testcases\Signup_Form\../TestData/Testdata_Signup.xlsx but file does not exist.</msg>
</errors>
</robot>
